"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-16 00:01:43.311750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("zpid", sa.Text(), nullable=False),
        sa.Column("img_src", sa.Text(), nullable=True),
        sa.Column("detail_url", sa.Text(), nullable=True),
        sa.Column("price", sa.Text(), nullable=True),
        sa.Column("unformatted_price", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("address_street", sa.Text(), nullable=True),
        sa.Column("address_city", sa.Text(), nullable=True),
        sa.Column("address_state", sa.Text(), nullable=True),
        sa.Column("address_zipcode", sa.Text(), nullable=True),
        sa.Column("beds", sa.Integer(), nullable=True),
        sa.Column("baths", sa.Float(), nullable=True),
        sa.Column("area", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("home_type", sa.Text(), nullable=True),
        sa.Column("home_status", sa.Text(), nullable=True),
        sa.Column("time_on_zillow", sa.Text(), nullable=True),
        sa.Column("flex_text", sa.Text(), nullable=True),
        sa.Column(
            "keep_updated", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
        sa.Column(
            "remove_listing",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("passes_preset_filters", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("zpid"),
    )
    op.create_table(
        "underwritings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "series_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("copied_from_id", sa.Integer(), nullable=True),
        sa.Column("zpid", sa.Text(), nullable=True),
        sa.Column("market_id", sa.Integer(), nullable=True),
        sa.Column("analyst_id", sa.Integer(), nullable=True),
        sa.Column("approver_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_reference",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("deal_status", sa.String(length=50), nullable=True),
        sa.Column(
            "deal_added",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deal_submitted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deal_approved", sa.DateTime(timezone=True), nullable=True),
        sa.Column("property_pending", sa.Boolean(), nullable=True),
        sa.Column("is_automated", sa.Boolean(), nullable=True),
        sa.Column("property_address", sa.String(length=255), nullable=True),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("days_on_market", sa.Integer(), nullable=True),
        sa.Column("sleep_count_low", sa.Integer(), nullable=True),
        sa.Column("sleep_count_high", sa.Integer(), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_oop", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("prr", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("budget_to_pp", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "low_gross_revenue", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "mid_gross_revenue", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "high_gross_revenue", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("l_cash_on_cash", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("m_cash_on_cash", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("h_cash_on_cash", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("turnkey", sa.Boolean(), nullable=True),
        sa.Column("furnished", sa.Boolean(), nullable=True),
        sa.Column("luxury", sa.Boolean(), nullable=True),
        sa.Column("tax_efficient", sa.Boolean(), nullable=True),
        sa.Column("new_construction", sa.Boolean(), nullable=True),
        sa.Column("existing_airbnb", sa.Boolean(), nullable=True),
        sa.Column("arv", sa.Boolean(), nullable=True),
        sa.Column("high_cash_on_cash", sa.Boolean(), nullable=True),
        sa.Column("low_cash_on_cash", sa.Boolean(), nullable=True),
        sa.Column("add_inground_pool", sa.Boolean(), nullable=True),
        sa.Column("renovation_level", sa.SmallInteger(), nullable=True),
        sa.Column("deal_complexity", sa.SmallInteger(), nullable=True),
        sa.Column("waterfront", sa.Boolean(), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=True),
        sa.Column("can_support_cohost", sa.Boolean(), nullable=True),
        sa.Column("market_type", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("execution_type", sa.String(length=50), nullable=True),
        sa.Column("seasonality", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("regulatory_clarity", sa.String(length=50), nullable=True),
        sa.Column("offer_competitiveness", sa.String(length=50), nullable=True),
        sa.Column("core_value_driver", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("cash_flow_quality", sa.String(length=50), nullable=True),
        sa.Column("view_quality", sa.String(length=50), nullable=True),
        sa.Column("pool_type", sa.String(length=50), nullable=True),
        sa.Column("primary_guest_avatar", sa.String(length=50), nullable=True),
        sa.Column("target_demographic", sa.String(length=50), nullable=True),
        sa.Column("listing_url", sa.Text(), nullable=True),
        sa.Column("loom_vid", sa.Text(), nullable=True),
        sa.Column("deal_pitch", sa.Text(), nullable=True),
        sa.Column("video_walkthrough", sa.Text(), nullable=True),
        sa.Column("survey", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("deal_score", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="adus", nullable=True),
        sa.Column("sheet_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "deal_status IS NULL OR deal_status IN ('template_generated', 'analyst_started', 'analyst_completed', 'delete_zillow', 'delete_deal', 'maybe', 're_forecast_revenue', 'awaiting_realtor_details', 'present_to_clients', 'client_under_contract', 'training_deal', 'previously_underwritten_no_status')",
            name="ck_underwritings_deal_status",
        ),
        sa.CheckConstraint(
            "deal_score IS NULL OR (deal_score >= 1 AND deal_score <= 100)",
            name="ck_underwritings_deal_score",
        ),
        sa.ForeignKeyConstraint(
            ["copied_from_id"], ["underwritings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["zpid"], ["properties.zpid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "series_id", "version", name="uq_underwritings_series_version"
        ),
    )
    op.create_index(
        "uq_underwritings_reference_zpid",
        "underwritings",
        ["zpid"],
        unique=True,
        postgresql_where=sa.text("is_reference IS TRUE"),
    )
    op.create_index(
        "uq_underwritings_sheet_number",
        "underwritings",
        ["sheet_number"],
        unique=True,
        postgresql_where=sa.text("sheet_number IS NOT NULL"),
    )
    op.create_table(
        "training_submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column("reference_underwriting_id", sa.Integer(), nullable=True),
        sa.Column("zpid", sa.Text(), nullable=False),
        sa.Column("accuracy", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reference_underwriting_id"], ["underwritings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["zpid"], ["properties.zpid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_training_submissions_underwriting_id",
        "training_submissions",
        ["underwriting_id"],
        unique=False,
    )
    op.create_index(
        "ix_training_submissions_zpid", "training_submissions", ["zpid"], unique=False
    )
    op.create_table(
        "uw_comp_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column("listing_url", sa.Text(), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("sleeps", sa.Integer(), nullable=True),
        sa.Column(
            "is_favourite",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("has_pool", sa.Boolean(), nullable=True),
        sa.Column("has_hot_tub", sa.Boolean(), nullable=True),
        sa.Column("has_sauna", sa.Boolean(), nullable=True),
        sa.Column("has_mini_golf", sa.Boolean(), nullable=True),
        sa.Column("has_game_room", sa.Boolean(), nullable=True),
        sa.Column("has_pickleball", sa.Boolean(), nullable=True),
        sa.Column("has_movie_theater", sa.Boolean(), nullable=True),
        sa.Column("has_playground", sa.Boolean(), nullable=True),
        sa.Column("has_waterfront", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uw_comp_sets_underwriting_id",
        "uw_comp_sets",
        ["underwriting_id"],
        unique=False,
    )
    op.create_table(
        "uw_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column(
            "purchase_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "y1_coc_incl_tax_savings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "forecasted_revenue", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "cleaning_cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "property_taxes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "zillow_property", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("analyst_notes", sa.Text(), nullable=True),
        sa.Column("construction_and_design_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_uw_details_underwriting_id", "uw_details", ["underwriting_id"], unique=True
    )
    op.create_table(
        "uw_operating_expenses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column("expense_name", sa.String(length=255), nullable=True),
        sa.Column("monthly_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uw_operating_expenses_underwriting_id",
        "uw_operating_expenses",
        ["underwriting_id"],
        unique=False,
    )
    op.create_table(
        "uw_optimization_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("metric", sa.Text(), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("spec", sa.Text(), nullable=True),
        sa.Column("tier", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uw_optimization_items_underwriting_id",
        "uw_optimization_items",
        ["underwriting_id"],
        unique=False,
    )
    op.create_table(
        "uw_taxes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("underwriting_id", sa.Integer(), nullable=False),
        sa.Column(
            "land_assumptions_pct", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column(
            "sla_multiplier_pct", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column(
            "improvement_basis", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "estimated_short_life_assets",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column("bonus_amount_pct", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("tax_rate_pct", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "y1_loss_from_depreciation",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column("tax_savings", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["underwriting_id"], ["underwritings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_uw_taxes_underwriting_id", "uw_taxes", ["underwriting_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_uw_taxes_underwriting_id", table_name="uw_taxes")
    op.drop_table("uw_taxes")
    op.drop_index(
        "ix_uw_optimization_items_underwriting_id", table_name="uw_optimization_items"
    )
    op.drop_table("uw_optimization_items")
    op.drop_index(
        "ix_uw_operating_expenses_underwriting_id", table_name="uw_operating_expenses"
    )
    op.drop_table("uw_operating_expenses")
    op.drop_index("uq_uw_details_underwriting_id", table_name="uw_details")
    op.drop_table("uw_details")
    op.drop_index("ix_uw_comp_sets_underwriting_id", table_name="uw_comp_sets")
    op.drop_table("uw_comp_sets")
    op.drop_index("ix_training_submissions_zpid", table_name="training_submissions")
    op.drop_index(
        "ix_training_submissions_underwriting_id", table_name="training_submissions"
    )
    op.drop_table("training_submissions")
    op.drop_index(
        "uq_underwritings_sheet_number",
        table_name="underwritings",
        postgresql_where=sa.text("sheet_number IS NOT NULL"),
    )
    op.drop_index(
        "uq_underwritings_reference_zpid",
        table_name="underwritings",
        postgresql_where=sa.text("is_reference IS TRUE"),
    )
    op.drop_table("underwritings")
    op.drop_table("properties")
    # ### end Alembic commands ###
